fix: generate ssh keys automatically when creating a aks cluster
redkubes/otomi-cluster pull request #1
Opened 2021-05-05 18:10 UTC by mojtabaimani

adding the flag to generate ssh key automatically to the az cli.

2021-05-05 18:15 UTC, Morriz reviewed
I am not sure if you understand yet that you can already pass this option via the configuration.

2021-05-05 18:15 UTC, Morriz commented on tpl/azure-create.sh
> +echo "az aks create -n '$cluster_name' -g '$aks_rg' --generate-ssh-keys --zones $(y _ zones) --load-balancer-outbound-ips \$egress_ip_id,\$ingress_ip_id $(y aks.create) $(y aks.nodePoolDefaults)\
why make this mandatory when it is now optional?

2021-05-06 06:57 UTC, j-zimnowoda requested changes

2021-05-06 06:57 UTC, j-zimnowoda commented on tpl/azure-create.sh
> +echo "az aks create -n '$cluster_name' -g '$aks_rg' --generate-ssh-keys --zones $(y _ zones) --load-balancer-outbound-ips \$egress_ip_id,\$ingress_ip_id $(y aks.create) $(y aks.nodePoolDefaults)\
@mojtabaimani please follow Maurice advice.
Take a look at `otomi-clusters/clouds/azure/default.yaml:15`
Then in `mojtaba.yaml` file you can set this flag
I just do not understand why some azure users need to set and the others not....

2021-05-06 08:49 UTC, closed without merging

2021-05-06 08:49 UTC, mojtabaimani commented
we have `generate-ssh-keys: true` in otomi-clusters repository.